import axios from "axios";
import { IntentAction, IntentResult, LLMResponse } from "./intent.types.js";
import { cleanAndParseJSON } from "./ai.service.js";
import { getBrainContext } from "./intent.context.service.js";

// ═══════════════════════════════════════════════════════════════════════════════
// INTENT SERVICE - Fixed with RESEARCH_BRAIN & Proper Email Body
// ═══════════════════════════════════════════════════════════════════════════════

// ─── Types ───────────────────────────────────────────────────────────────────

export interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

export interface ClassifyIntentParams {
  userText: string;
  userId: string;
  chatHistory?: ChatMessage[];
}

// ─── Config ──────────────────────────────────────────────────────────────────

const LLM_API_URL = process.env.LLM_API_URL ?? "http://localhost:1234/v1/chat/completions";
const LLM_MODEL = process.env.LLM_MODEL ?? "local-model";
const LLM_TIMEOUT = Number(process.env.LLM_TIMEOUT ?? 30_000);

// ─── System Prompt with RESEARCH_BRAIN ──────────────────────────────────────

function buildJarvisSystemPrompt(
  brainContext: string,
  chatHistory?: ChatMessage[]
): string {
  // Historia rozmowy
  let historySection = '';
  if (chatHistory && chatHistory.length > 0) {
    historySection = '\n<CHAT_HISTORY>\n';
    const recentHistory = chatHistory.slice(-5);
    recentHistory.forEach(msg => {
      const role = msg.role === 'user' ? 'User' : 'Jarvis';
      historySection += `${role}: ${msg.content}\n`;
    });
    historySection += '</CHAT_HISTORY>\n';
  }

  return `You are JARVIS - AI assistant. Style: konkretny, pragmatyczny, pomocny. Zwrot: "mordo".

CURRENT DATE: ${new Date().toISOString()}

${historySection}

<BRAIN_CONTEXT>
${brainContext}
</BRAIN_CONTEXT>

CRITICAL: Respond ONLY with valid JSON - NO markdown, NO backticks, NO extra text.

JSON Format:
{
  "action": "SAVE_ONLY" | "SAVE_SEARCH" | "RESEARCH_BRAIN" | "SAVE_MAIL" | "CREATE_EVENT",
  "reasoning": "short technical explanation",
  "answer": "natural Polish response with 'mordo' style",
  "eventData": {...}  // ONLY if CREATE_EVENT
  "emailData": {      // ONLY if SAVE_MAIL
    "recipient": "email@example.com",
    "subject": "Subject line",
    "body": "Full email content generated by you"
  }
}

CLASSIFICATION RULES:

1. CREATE_EVENT → date/time or reminder mentioned
   Extract: title, startDate (ISO 8601), category
   
2. SAVE_MAIL → email sending request
   IMPORTANT: Generate FULL email body in "emailData.body"
   Extract recipient if found, suggest subject
   
3. RESEARCH_BRAIN → user asks about information that:
   - Is NOT in current <BRAIN_CONTEXT>
   - Relates to user's own data/memories/notes
   - Example: "Co mi mówiłeś o projekcie X?" when project X not in context
   Answer: "Zaraz sprawdzę w pamięci, mordo. Chwilę..."
   
4. SAVE_SEARCH → user needs CURRENT info from internet:
   - News, prices, weather, latest updates
   - Example: "Jaka jest pogoda?" or "Co nowego w AI?"
   Answer: "Sprawdzam w internecie, mordo. Chwila."

5. SAVE_ONLY → general conversation, greetings, simple questions
   Answer based on available context

AGENTIC LOGIC:
- If user asks about something and <BRAIN_CONTEXT> is empty → use RESEARCH_BRAIN
- If user asks about current events/news → use SAVE_SEARCH
- If user asks about their past notes/memories → use RESEARCH_BRAIN
- DON'T say "nie wiem" - use appropriate research action instead!

FEW-SHOT EXAMPLES:

Example 1 - Greeting:
User: "Jak się masz?"
{
  "action": "SAVE_ONLY",
  "reasoning": "Greeting, no action needed",
  "answer": "Wszystko git, mordo. Gotowy do roboty."
}

Example 2 - Reminder:
User: "Przypomnij mi jutro o 10 o spotkaniu"
{
  "action": "CREATE_EVENT",
  "reasoning": "Reminder with time",
  "answer": "Jasne, mordo. Ustawiam na jutro o 10:00.",
  "eventData": {
    "title": "Spotkanie",
    "startDate": "2024-12-26T10:00:00Z",
    "category": "reminder"
  }
}

Example 3 - Email with BODY:
User: "Wyślij mail do john@example.com że projekt jest opóźniony"
{
  "action": "SAVE_MAIL",
  "reasoning": "Email request with recipient and context",
  "answer": "Okej, mordo. Wysyłam do john@example.com.",
  "emailData": {
    "recipient": "john@example.com",
    "subject": "Aktualizacja statusu projektu",
    "body": "Cześć,\\n\\nChciałem poinformować, że projekt jest obecnie opóźniony. Pracuję nad rozwiązaniem problemu i wrócę z aktualizacją wkrótce.\\n\\nPozdrawiam"
  }
}

Example 4 - Internet Search:
User: "Jaka jest pogoda w Warszawie?"
{
  "action": "SAVE_SEARCH",
  "reasoning": "Current info needed from internet",
  "answer": "Sprawdzam pogodę w internecie, mordo. Chwila."
}

Example 5 - Brain Research (empty context):
User: "Co mi mówiłeś o projekcie AI na uczelni?"
Brain Context: 💭 Brak relevantnych wspomnień
{
  "action": "RESEARCH_BRAIN",
  "reasoning": "User asks about past info, not in current context",
  "answer": "Zaraz sprawdzę w pamięci, mordo. Chwilę..."
}

Example 6 - Brain Research (incomplete context):
User: "Podaj mi szczegóły tego projektu"
Brain Context: 📚 Wspomnienia: [tylko tytuł projektu]
{
  "action": "RESEARCH_BRAIN",
  "reasoning": "Context incomplete, need deeper search",
  "answer": "Mam tylko podstawowe info. Zagłębię się, mordo."
}

JARVIS STYLE:
- Be proactive: use research actions when needed
- "mordo" instead of "sir"
- Concise (2-3 sentences)
- Don't apologize for lack of knowledge - take action!

DATE PARSING:
- "jutro o 10" → tomorrow 10:00
- "w piątek" → next Friday 09:00
- "za tydzień" → +7 days

REMEMBER: 
- ONLY valid JSON
- NO markdown, NO backticks
- Generate FULL email body in emailData.body
- Use RESEARCH_BRAIN when context is incomplete
- Use SAVE_SEARCH for current internet info`;
}

// ─── Keyword Fallback ────────────────────────────────────────────────────────

const SEARCH_KEYWORDS = [
  /pogoda/i, /cena/i, /aktualn/i, /najnowsz/i, /dzisiaj/i, /teraz/i,
  /weather/i, /price/i, /current/i, /latest/i, /today/i, /now/i,
];

const RESEARCH_KEYWORDS = [
  /co (mi |)mówił/i, /pamiętasz/i, /przypomnij mi o/i, /znajdź w notatkach/i,
  /what did (I|you) say/i, /do you remember/i, /find in my notes/i,
];

const MAIL_KEYWORDS = [
  /wyślij (e-?mail|mail|wiadomość)/i, /napisz (do|mail)/i,
  /send (an? )?(e-?mail|message)/i,
];

const EVENT_KEYWORDS = [
  /przypomnij/i, /przypomnienie/i, /spotkanie/i, /kalendarz/i,
  /jutro/i, /dziś/i, /w piątek/i,
  /remind/i, /reminder/i, /meeting/i, /tomorrow/i,
];

function keywordFallback(text: string): IntentResult {
  // Research Brain ma wysoki priorytet
  if (RESEARCH_KEYWORDS.some((re) => re.test(text))) {
    return { 
      action: "RESEARCH_BRAIN", 
      reasoning: "Keyword match: memory/notes",
      answer: "Zaraz sprawdzę w pamięci, mordo."
    };
  }

  if (EVENT_KEYWORDS.some((re) => re.test(text))) {
    return { 
      action: "CREATE_EVENT", 
      reasoning: "Keyword match: date/reminder",
      answer: "Jasne, mordo. Ustawiam przypomnienie.",
      eventData: {
        title: text.substring(0, 100),
        startDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
        category: 'reminder'
      }
    };
  }
  
  if (MAIL_KEYWORDS.some((re) => re.test(text))) {
    return { 
      action: "SAVE_MAIL", 
      reasoning: "Keyword match: send/mail",
      answer: "Okej, mordo. Przygotowuję maila."
    };
  }
  
  if (SEARCH_KEYWORDS.some((re) => re.test(text))) {
    return { 
      action: "SAVE_SEARCH", 
      reasoning: "Keyword match: current/latest",
      answer: "Sprawdzam w internecie, mordo."
    };
  }
  
  return { 
    action: "SAVE_ONLY", 
    reasoning: "General conversation",
    answer: "Łap, mordo. Jestem jak coś."
  };
}

// ─── JSON Parser ─────────────────────────────────────────────────────────────

const VALID_ACTIONS = new Set<IntentAction>([
  "SAVE_ONLY", 
  "SAVE_SEARCH",
  "RESEARCH_BRAIN", // ← NOWE!
  "SAVE_MAIL", 
  "CREATE_EVENT"
]);

function parseIntentJSON(raw: string): IntentResult | null {
  const parsed = cleanAndParseJSON(raw);
  
  if (!parsed) {
    console.warn('[IntentService] cleanAndParseJSON returned null');
    return null;
  }

  try {
    const action = parsed["action"];
    const reasoning = typeof parsed["reasoning"] === "string" 
      ? parsed["reasoning"] 
      : "No reasoning provided";
    const answer = typeof parsed["answer"] === "string"
      ? parsed["answer"]
      : "Okej, mordo.";

    if (typeof action === "string" && VALID_ACTIONS.has(action as IntentAction)) {
      const result: IntentResult = { 
        action: action as IntentAction, 
        reasoning,
        answer
      };
      
      // Dodaj eventData jeśli CREATE_EVENT
      if (action === "CREATE_EVENT" && parsed["eventData"]) {
        result.eventData = parsed["eventData"] as IntentResult["eventData"];
      }
      
      // Dodaj emailData jeśli SAVE_MAIL (z body!)
      if (action === "SAVE_MAIL" && parsed["emailData"]) {
        result.emailData = parsed["emailData"] as IntentResult["emailData"];
      }
      
      return result;
    }
  } catch (err) {
    console.error("[IntentService] JSON parse failed:", err);
  }

  return null;
}

// ─── Main Service ────────────────────────────────────────────────────────────

/**
 * Klasyfikuje intencję z RESEARCH_BRAIN support
 */
export async function classifyIntent(params: ClassifyIntentParams): Promise<IntentResult> {
  const { userText, userId, chatHistory = [] } = params;
  
  console.log('[IntentService] ═══ Classifying intent ═══');
  console.log('[IntentService] User:', userId);
  console.log('[IntentService] Text:', userText);

  try {
    // 1. Pobierz kontekst mózgu
    console.log('[IntentService] Fetching brain context...');
    const brainContext = await getBrainContext(userId, userText);
    console.log('[IntentService] Brain context retrieved:', brainContext.hasContext);

    // 2. Zbuduj System Prompt
    const systemPrompt = buildJarvisSystemPrompt(
      brainContext.synapticTree,
      chatHistory
    );

    // 3. Wywołaj LLM z temperature 0.1
    console.log('[IntentService] Calling LLM with temperature=0.1...');
    
    const response = await axios.post<LLMResponse>(
      LLM_API_URL,
      {
        model: LLM_MODEL,
        temperature: 0.1, // Stabilność!
        max_tokens: 800,  // Więcej dla email body
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userText },
        ],
      },
      { timeout: LLM_TIMEOUT }
    );

    const rawContent = response.data?.choices?.[0]?.message?.content ?? "";
    console.log("[IntentService] LLM raw output length:", rawContent.length);

    // 4. Parsuj przez cleanAndParseJSON
    const llmResult = parseIntentJSON(rawContent);
    
    if (llmResult) {
      console.log("[IntentService] ✓ Successfully parsed:", {
        action: llmResult.action,
        hasAnswer: !!llmResult.answer,
        hasEmailBody: !!(llmResult.emailData?.body)
      });
      return llmResult;
    }

    console.warn("[IntentService] ⚠️ LLM output not parseable → keyword fallback");
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`[IntentService] ❌ Error: ${message}`);
  }

  // 5. Keyword fallback
  const kwResult = keywordFallback(userText);
  console.log("[IntentService] Keyword fallback result:", kwResult.action);
  return kwResult;
}

// ─── Helper: Validate Event Data ────────────────────────────────────────────

export function validateEventData(eventData?: IntentResult["eventData"]): {
  isValid: boolean;
  normalized?: IntentResult["eventData"];
  error?: string;
} {
  if (!eventData) {
    return { isValid: false, error: "Missing eventData" };
  }

  if (!eventData.title || !eventData.startDate) {
    return { isValid: false, error: "Missing title or startDate" };
  }

  const startDate = new Date(eventData.startDate);
  if (isNaN(startDate.getTime())) {
    return { isValid: false, error: "Invalid startDate format" };
  }

  if (eventData.endDate) {
    const endDate = new Date(eventData.endDate);
    if (isNaN(endDate.getTime())) {
      return { isValid: false, error: "Invalid endDate format" };
    }
    
    if (endDate <= startDate) {
      return { isValid: false, error: "endDate must be after startDate" };
    }
  }

  return {
    isValid: true,
    normalized: {
      title: eventData.title.trim(),
      description: eventData.description?.trim() || undefined,
      startDate: startDate.toISOString(),
      endDate: eventData.endDate ? new Date(eventData.endDate).toISOString() : undefined,
      category: eventData.category || 'other',
    },
  };
}
